import { HttpException, HttpStatus } from '@nestjs/common';

/**
 * Catálogo de códigos de error. La app decide qué hacer según `code`; el
 * `message` va en español porque se muestra tal cual al usuario.
 */
export const ErrorCode = {
  // Generales
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // Auth
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  OTP_NOT_REQUESTED: 'OTP_NOT_REQUESTED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_TOO_MANY_REQUESTS: 'OTP_TOO_MANY_REQUESTS',
  REGISTRATION_EXPIRED: 'REGISTRATION_EXPIRED',
  USER_DISABLED: 'USER_DISABLED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  SMS_INVALID_NUMBER: 'SMS_INVALID_NUMBER',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  // Cupones
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
  COUPON_MIN_NOT_REACHED: 'COUPON_MIN_NOT_REACHED',
  COUPON_EXHAUSTED: 'COUPON_EXHAUSTED',
  COUPON_ALREADY_USED: 'COUPON_ALREADY_USED',
  COUPON_FIRST_ORDER_ONLY: 'COUPON_FIRST_ORDER_ONLY',
  // Pedidos
  STORE_CLOSED: 'STORE_CLOSED',
  SCHEDULE_INVALID: 'SCHEDULE_INVALID',
  ADDRESS_OUT_OF_COVERAGE: 'ADDRESS_OUT_OF_COVERAGE',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  INVALID_PRODUCT_OPTIONS: 'INVALID_PRODUCT_OPTIONS',
  MIN_ORDER_NOT_REACHED: 'MIN_ORDER_NOT_REACHED',
  CASH_CHANGE_TOO_LOW: 'CASH_CHANGE_TOO_LOW',
  ORDER_NOT_DELIVERED: 'ORDER_NOT_DELIVERED',
  ORDER_ALREADY_RATED: 'ORDER_ALREADY_RATED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_ALREADY_TAKEN: 'ORDER_ALREADY_TAKEN',
  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',
  // Repartidor
  COURIER_HAS_ACTIVE_ORDER: 'COURIER_HAS_ACTIVE_ORDER',
  COURIER_NOT_AVAILABLE: 'COURIER_NOT_AVAILABLE',
  COLLECTION_REQUIRED: 'COLLECTION_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export class AppException extends HttpException {
  constructor(
    readonly code: ErrorCode,
    status: HttpStatus,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super({ code, message, details }, status);
  }

  static notFound(message: string) {
    return new AppException(ErrorCode.NOT_FOUND, HttpStatus.NOT_FOUND, message);
  }
}
